### ISSUE TITLE
release 0.3.0

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/flamel#13]
First release of the thin-CLI architecture (as described in discussion #12).

This release is **backwards incompatible** to the previous releases (the original plugin-based architecture). It will be pip installable.

**Comment by orbeckst** [comment]
flamel is already taken on PyPi. Do we have an opinion on the package name? 

- [ ] alchemlyb-flamel
- [ ] alchemistry-flamel
- [ ] alchemical-analysis
- [ ] ... better ideas?

cc: @xiki-tempula @dominikwille @davidlmobley

**Comment by orbeckst** [comment]
@xiki-tempula if you're happy with https://pypi.org/project/alchemistry-flamel/0.3.0rc2/ then we can make a release.

**Comment by orbeckst** [comment]
Also let me know who you are on pypi so that I can invite you as a owner of the pypi project (and the one on testpypi).

**Comment by orbeckst** [comment]
Also created https://github.com/alchemistry/flamel/releases/tag/v0.3.0rc2

Eventually, we want to add GH deployment workflow...

**Comment by orbeckst** [comment]
@xiki-tempula are you fine with a 0.3.0 release of flamel?

**Comment by xiki-tempula** [comment]
@orbeckst Sorry. I'm fine with a `rc` but I haven't had time to test it more thoroughly so is a bit reluctant to do a formal release. On the other hand, given that we are still at 0.X.X, we could just release a 0.3.1 if I found some other issue with it.

**Comment by orbeckst** [comment]
I ran the tests for the rc2 package and they passed. I think it's "good enough" for 0.3.0. Let's get it out and then fix if there's anything necessary.

**Comment by orbeckst** [comment]
My rc3 is failing the manual installation:
```
(alchemlyb39_dev) laptop:flamel oliver$ pip install -i https://test.pypi.org/simple/ alchemistry-flamel==0.3.0rc3
Looking in indexes: https://test.pypi.org/simple/
Collecting alchemistry-flamel==0.3.0rc3
  Downloading https://test-files.pythonhosted.org/packages/c4/02/6a1c95c34ca51a826663f6233a52ba6ef2c273f203deee4e8763ab6a3f43/alchemistry_flamel-0.3.0rc3-py3-none-any.whl (8.5 kB)
Collecting alchemlyb>=1.0
  Using cached https://test-files.pythonhosted.org/packages/c6/0a/323a85ede5a46873961f1f0ff0f6764d74895dc73abcfca009794a874fb1/alchemlyb-1.0.0-py3-none-any.whl (85 kB)
ERROR: Could not find a version that satisfies the requirement importlib-resources; python_version < "3.12" (from alchemistry-flamel) (from versions: none)
ERROR: No matching distribution found for importlib-resources; python_version < "3.12"
```
Need to check, maybe I made a mistake in pyproject.toml.

**Comment by orbeckst** [comment]
Now it worked... maybe had to do  some env  cleaning.  Will cut the 0.3.0

**Comment by orbeckst** [comment]
```
pip install -i https://test.pypi.org/simple/ alchemistry-flamel==0.3.0
```
works ... on to the final release!

**Comment by orbeckst** [comment]
Released, tweeted, done.
